- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
   - name: apt update
     command: sudo apt-get update
   - name: install python & pip
     command: sudo apt install -y python-pip
   - name: Install docker
     command: sudo apt-get install -y docker.io
     become: yes
     become_user: root
   - name: start docker service
     command: sudo systemctl start docker
     become: yes
   - name : Run the Bank application
     command: sudo docker run -itd -p 8084:8081 faisalhkdocker/bankingproject:latest 
